//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        public string component_name { get; set; }
        public string component_number { get; set; }
        public decimal component_amount { get; set; }
        public Nullable<System.Guid> product_guid { get; set; }
        public int component_clusterkey { get; set; }
    
        public virtual component component1 { get; set; }
        public virtual component component2 { get; set; }
    }
}
