//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_login
    {
        public string user_login { get; set; }
        public string user_password { get; set; }
        public string user_fname { get; set; }
        public string user_lname { get; set; }
        public string user_phone_number { get; set; }
        public System.Guid company_guid { get; set; }
        public string user_type { get; set; }
        public byte[] user_register_date { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
