//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public string location_name { get; set; }
        public string storage_area { get; set; }
        public System.Guid location_guid { get; set; }
        public System.Guid company_guid { get; set; }
        public int location_clusterkey { get; set; }
        public System.Guid product_guid { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
    }
}
